# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_teams', '0002_add_simple_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('member', 'member'), ('manager', 'manager'), ('owner', 'owner')], default='member', max_length=20, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='state',
            field=models.CharField(choices=[('applied', 'applied'), ('invited', 'invited'), ('declined', 'declined'), ('rejected', 'rejected'), ('accepted', 'accepted'), ('auto-joined', 'auto joined')], max_length=20, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='simplemembership',
            name='role',
            field=models.CharField(choices=[('member', 'member'), ('manager', 'manager'), ('owner', 'owner')], default='member', max_length=20, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='simplemembership',
            name='state',
            field=models.CharField(choices=[('applied', 'applied'), ('invited', 'invited'), ('declined', 'declined'), ('rejected', 'rejected'), ('accepted', 'accepted'), ('auto-joined', 'auto joined')], max_length=20, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='simpleteam',
            name='manager_access',
            field=models.CharField(choices=[('add someone', 'add someone'), ('invite someone', 'invite someone')], max_length=20, verbose_name='manager access'),
        ),
        migrations.AlterField(
            model_name='simpleteam',
            name='member_access',
            field=models.CharField(choices=[('open', 'open'), ('application', 'by application'), ('invitation', 'by invitation')], max_length=20, verbose_name='member access'),
        ),
        migrations.AlterField(
            model_name='team',
            name='manager_access',
            field=models.CharField(choices=[('add someone', 'add someone'), ('invite someone', 'invite someone')], max_length=20, verbose_name='manager access'),
        ),
        migrations.AlterField(
            model_name='team',
            name='member_access',
            field=models.CharField(choices=[('open', 'open'), ('application', 'by application'), ('invitation', 'by invitation')], max_length=20, verbose_name='member access'),
        ),
    ]
