# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-09 22:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pinax_teams', '0002_auto_20160309_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('applied', 'applied'), ('invited', 'invited'), ('declined', 'declined'), ('rejected', 'rejected'), ('accepted', 'accepted'), ('auto-joined', 'auto joined')], max_length=20, verbose_name='state')),
                ('role', models.CharField(choices=[('member', 'member'), ('manager', 'manager'), ('owner', 'owner')], default='member', max_length=20, verbose_name='role')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created')),
                ('invite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='invitations.JoinInvitation', verbose_name='invite')),
            ],
            options={
                'verbose_name': 'Simple Membership',
                'verbose_name_plural': 'Simple Memberships',
            },
        ),
        migrations.RenameModel(
            old_name='Role',
            new_name='SimpleTeam',
        ),
        migrations.AlterModelOptions(
            name='membership',
            options={'verbose_name': 'Membership', 'verbose_name_plural': 'Memberships'},
        ),
        migrations.AlterModelOptions(
            name='simpleteam',
            options={'verbose_name': 'Simple Team', 'verbose_name_plural': 'Simple Teams'},
        ),
        migrations.AddField(
            model_name='simplemembership',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='pinax_teams.SimpleTeam', verbose_name='team'),
        ),
        migrations.AddField(
            model_name='simplemembership',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterUniqueTogether(
            name='simplemembership',
            unique_together=set([('team', 'user', 'invite')]),
        ),
    ]
